config/routes.rb
EmoneyServer::Application.routes.draw do
  namespace :api do
    namespace :v1 do
      devise_scope :user do
        post 'sessions' => 'sessions#create', :as => 'login'
        delete 'sessions' => 'sessions#destroy', :as => 'logout'
      end
    end
  end
  
  namespace :admin do
    resources :users do
      resources :accounts
    end
    resources :syncs
  end
  resources :presence_logs
  resources :park_logs
  resources :accounts do
    member do
      get :top_up
      post :process_top_up
    end
    resources :transaction_logs do
      get :cancel, on: :member
    end
    resources :presence_logs
    resources :park_logs
  end
  resources :payers, controller: "accounts" do
    resources :transaction_logs do
      get :cancel, on: :member
    end
  end
  resources :merchants, controller: "accounts" do
    resources :transaction_logs do
      get :cancel, on: :member
    end
  end
  
  resources :park_meters, controller: "accounts" do
    resources :park_logs
  end
  
  resources :attendance_machines, controller: "accounts" do
    resources :presence_logs do
      
    end
  end
  devise_for :users
  devise_scope :user do
    get '/logout' => "devise/sessions#destroy"
    get '/profile' => "devise/registrations#edit"
  end
  
  get '/update_key' => "home#update_key"
  get '/create_account/:account' => "accounts#create_account"
  post '/sync' => "transaction_logs#sync"
  post '/register' => "accounts#register"
  post '/presence' => "presence_logs#presence"
  post '/park' => "park_logs#park"
  post '/get_key' => "accounts#get_key"
  

  root 'home#index'
  get "/dashboard" => "home#index"

end

app/models/transaction_log.rb
class TransactionLog
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Attributes::Dynamic
  embedded_in :account
  field :amount, type: Float
  field :log_type
  field :payer_id, type: Integer
  field :merchant_id, type: Integer
  field :timestamp, type: Integer
  field :cancel, type: Boolean, default: false
  field :status, type: String, default: 0
  field :num, type: Integer
  field :binary_id
  
  validate :check_account_balance
  after_create :update_account_balance
  def self.columns
    self.fields.collect{|c| c[1]}
  end

  def check_account_balance
    if (account.balance + amount) < 0
      errors.add(:amount, "Account balance is not enough for this transaction's amount")
    end
  end
  
  def update_account_balance
    account.balance += amount
    account.save(validate: false)
  end
  
  def merchant
    Account.where(accn: merchant_id.to_s).first
  end
  
  def payer
    Account.where(accn: payer_id.to_s).first
  end
  
  def cancel_transaction
    unless cancel
      unless log_type == "TopUp"
      # cek merchant atau payer
        if account.is_merchant?
          merchant.transaction_logs.create(amount: -(amount), payer_id: payer_id, merchant_id: merchant_id, timestamp: Time.now.to_i, cancel: true, status: "completed", num: "1")
          payer.transaction_logs.create(amount: amount, payer_id: payer_id, merchant_id: merchant_id, timestamp: Time.now.to_i, cancel: true, status: "completed", num: "1")
        elsif account.is_payer?
          merchant.transaction_logs.create(amount: amount, payer_id: payer_id, merchant_id: merchant_id, timestamp: Time.now.to_i, cancel: true, status: "completed", num: "1")
          payer.transaction_logs.create(amount: -(amount), payer_id: payer_id, merchant_id: merchant_id, timestamp: Time.now.to_i, cancel: true, status: "completed", num: "1")
        end
      else
        account.transaction_logs.create(amount: -(amount), payer_id: payer_id, merchant_id: merchant_id, timestamp: Time.now.to_i, cancel: true, status: "completed", num: "1")
      end
    end
  end
end

app/controllers/transaction_logs_controller.rb
class TransactionLogsController < InheritedResources::Base
  before_filter :authenticate_user!, except: [:sync]
  skip_before_filter :verify_authenticity_token, :if => Proc.new { |c| c.request.format == 'application/json' }

  def index
    @account = Account.find params[:account_id]
    @transaction_logs = @account.transaction_logs.order_by("created_at desc").page(params[:page]).per(10)
  end
  
  def show
    @account = Account.find params[:account_id]
    @transaction_log = @account.transaction_logs.find params["id"]
  end

  def sync
    header = JSON.parse params[:header]
    logs_row = params[:logs]
    signature = header["signature"]
    last_sync_at = header["last_sync_at"].to_i # to generate new key
    start_balance = header["balance"]
    @error_logs = []
    if signature != Digest::SHA256.hexdigest(logs_row).upcase
      @error = "Hash not match"
    else
      account = Account.where(accn: header["ACCN"].to_s).first
      @sync = Sync.new(account: account, data: params[:data], header: params[:header], logs: params[:logs], hashed_logs: signature)
      if @sync.save
        if account
          logs = JSON.parse(logs_row)
          logs.each do |log|
            # check merchant & payer
            if header["ACCN"].to_s[0] == "1"
              merchant = Merchant.where(accn: header["ACCN"].to_s).first
              payer = Payer.where(accn: log["ACCN-P"].to_s).first
              if merchant && payer
                # cari timestamp kalau ketemu update log / tidak create log
                log_payer = payer.transaction_logs.where(timestamp: log["TS"]).first
                if log_payer
                  log_payer.merchant_id = log["ACCN-M"]
                  log_payer.status = "completed"
                else
                  log_payer = payer.transaction_logs.build(
                    merchant_id: log["ACCN-M"],
                    payer_id: log["ACCN-P"],
                    amount: -(log["AMNT"]),
                    log_type: log["PT"],
                    timestamp: log["TS"],
                    status: log["STAT"],
                    cancel: log["CNL"],
                    num: log["NUM"],
                    binary_id: log["BinaryID"]
                  )
                end
                if log_payer.valid? && log_payer.save
                  log_merchant = merchant.transaction_logs.where(timestamp: log["TS"]).first
                  unless log_merchant
                    log_merchant = merchant.transaction_logs.create(
                      merchant_id: log["ACCN-M"],
                      payer_id: log["ACCN-P"],
                      amount: log["AMNT"],
                      log_type: log["PT"],
                      timestamp: log["TS"],
                      status: "completed",
                      cancel: log["CNL"],
                      num: log["NUM"],
                      binary_id: log["BinaryID"]
                    )
                  end
                else
                  # better error
                  @error = "Error Payer: #{log_payer.errors.messages}"
                  @error_logs << log["NUM"]
                end
              else
                # need to block
                @error = "Invalid Transactions"
              end
            else
              # 2
              payer = Payer.where(accn: header["ACCN"].to_s).first
              merchant = Merchant.where(accn: log["ACCN-M"].to_s).first
              if payer
                # cari timestamp kalau ketemu update log / tidak create log
                log_payer = payer.transaction_logs.where(timestamp: log["TS"]).first
                if log_payer
                  log_payer.merchant_id = log["ACCN-M"]
                else
                  log_payer = payer.transaction_logs.create(
                    merchant_id: log["ACCN-M"],
                    payer_id: log["ACCN-P"],
                    amount: -(log["AMNT"]),
                    log_type: log["PT"],
                    timestamp: log["TS"],
                    status: log["STAT"],
                    cancel: log["CNL"],
                    num: log["NUM"],
                    binary_id: log["BinaryID"]
                  )
                end
              else
                # need to block
                @error = "Invalid Transactions"
              end
            end
          end
          log_payer = nil
          log_merchant = nil
        else
          @error = "Account not found"
        end
      else
        @error = "Duplicate Transaction"
      end
    end
    @sync.error_logs = @error if @error
    @sync.save
    @server = ServerSetting.first
    @renew_key = false
    if last_sync_at < @server.updated_at.to_i
      @renew_key = true
      @key = @server.key
    end
    @account_balance = Account.where(accn: header["ACCN"].to_s).first.balance.to_i if account
    respond_to do |format|
      format.json
      format.html
    end
  end
  
  def cancel
    @account = Account.find params[:account_id]
    @transaction_log = @account.transaction_logs.find params[:id]
    @transaction_log.cancel_transaction
    redirect_to account_transaction_logs_path(@account), notice: "Transaction has been cancelled"
  end
end

app/helpers/transaction_logs_helper.rb
module TransactionLogsHelper
end

app/views/transaction_logs/_form.html.erb
<%= simple_form_for @transaction_log, :html => { :class => 'form-vertical' } do |f| %>
  <%= f.input :amount %>
  <%= f.input :log_type %>
  <%= f.input :payer_id %>
  <%= f.input :merchant_id %>
  <%= f.input :timestamp %>
  <%= f.input :cancel %>
  <%= f.input :status %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                transaction_logs_path, :class => 'btn btn-default' %>
<% end %>

app/views/transaction_logs/edit.html.erb
<%- model_class = TransactionLog -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/transaction_logs/index.html.erb
<%- model_class = TransactionLog -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:amount) %></th>
      <th><%= model_class.human_attribute_name(:log_type) %></th>
      <th><%= model_class.human_attribute_name(:payer_id) %></th>
      <th><%= model_class.human_attribute_name(:merchant_id) %></th>
      <th><%= model_class.human_attribute_name(:timestamp) %></th>
      <th><%= model_class.human_attribute_name(:cancel) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @transaction_logs.each do |transaction_log| %>
      <tr>
        <td><%= link_to transaction_log.id, account_transaction_log_path(@account, transaction_log) %></td>
        <td><%= transaction_log.amount %></td>
        <td><%= transaction_log.log_type %></td>
        <td><%= transaction_log.payer_id %></td>
        <td><%= transaction_log.merchant_id %></td>
        <td><%= transaction_log.timestamp %></td>
        <td><%= transaction_log.cancel %></td>
        <td><%= transaction_log.status %></td>
        <td><%=l transaction_log.created_at %></td>
        <td>
          <%#= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_account_transaction_log_path(@account, transaction_log), :class => 'btn btn-default btn-xs' %>
          <%= link_to "cancel",
                      cancel_account_transaction_log_path(@account, transaction_log),
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="pagination">
  <%= paginate @transaction_logs %>
</div>

app/views/transaction_logs/new.html.erb
<%- model_class = TransactionLog -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/transaction_logs/show.html.erb
<%- model_class = TransactionLog -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:amount) %>:</strong></dt>
  <dd><%= @transaction_log.amount %></dd>
  <dt><strong><%= model_class.human_attribute_name(:log_type) %>:</strong></dt>
  <dd><%= @transaction_log.log_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:payer_id) %>:</strong></dt>
  <dd><%= @transaction_log.payer_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:merchant_id) %>:</strong></dt>
  <dd><%= @transaction_log.merchant_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:timestamp) %>:</strong></dt>
  <dd><%= @transaction_log.timestamp %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cancel) %>:</strong></dt>
  <dd><%= @transaction_log.cancel %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @transaction_log.status %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              account_transaction_logs_path(@account), :class => 'btn btn-default'  %>
<%#= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_transaction_log_path(@transaction_log), :class => 'btn btn-default' %>
<%#= link_to t('.destroy', :default => t("helpers.links.destroy")),
              transaction_log_path(@transaction_log),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>