config/routes.rb
EmoneyServer::Application.routes.draw do
  namespace :api do
    namespace :v1 do
      devise_scope :user do
        post 'sessions' => 'sessions#create', :as => 'login'
        delete 'sessions' => 'sessions#destroy', :as => 'logout'
      end
    end
  end
  
  namespace :admin do
    resources :users do
      resources :accounts
    end
    resources :syncs
  end
  resources :presence_logs
  resources :park_logs
  resources :accounts do
    member do
      get :top_up
      post :process_top_up
    end
    resources :transaction_logs do
      get :cancel, on: :member
    end
    resources :presence_logs
    resources :park_logs
  end
  resources :payers, controller: "accounts" do
    resources :transaction_logs do
      get :cancel, on: :member
    end
  end
  resources :merchants, controller: "accounts" do
    resources :transaction_logs do
      get :cancel, on: :member
    end
  end
  
  resources :park_meters, controller: "accounts" do
    resources :park_logs
  end
  
  resources :attendance_machines, controller: "accounts" do
    resources :presence_logs do
      
    end
  end
  devise_for :users
  devise_scope :user do
    get '/logout' => "devise/sessions#destroy"
    get '/profile' => "devise/registrations#edit"
  end
  
  get '/update_key' => "home#update_key"
  get '/create_account/:account' => "accounts#create_account"
  post '/sync' => "transaction_logs#sync"
  post '/register' => "accounts#register"
  post '/presence' => "presence_logs#presence"
  post '/park' => "park_logs#park"
  post '/get_key' => "accounts#get_key"
  

  root 'home#index'
  get "/dashboard" => "home#index"

end

app/models/sync.rb
class Sync
  include Mongoid::Document
  include Mongoid::Timestamps
  belongs_to :account
  field :data
  field :ip_address
  field :header
  field :logs
  field :hashed_logs
  field :error_logs
  
  validates :hashed_logs, presence: true#, uniqueness: {scope: :account_id} # check for reply attack
  def self.columns
    self.fields.collect{|c| c[1]}
  end
end

app/controllers/admin/syncs_controller.rb
class Admin::SyncsController < InheritedResources::Base
  before_filter :authenticate_user!
  
  protected
  def collection
    @syncs ||= end_of_association_chain.order(sort_column + " " + sort_direction).page(params[:page]).per(20)
  end
end

app/views/admin/syncs/_form.html.erb
<%= simple_form_for @sync, :html => { :class => 'form-vertical' } do |f| %>
  <%= f.input :header, as: :text, input_html: {rows: 20} %>
  <%= f.input :logs, as: :text, input_html: {rows: 20} %>
  <%= f.input :data, as: :text, input_html: {rows: 20} %>
  <%= f.input :error_logs, as: :text, input_html: {rows: 20} %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                admin_syncs_path, :class => 'btn btn-default' %>
<% end %>

app/views/admin/syncs/edit.html.erb
<%- model_class = Sync -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/syncs/index.html.erb
<%- model_class = Sync -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:header) %></th>
      <th><%= model_class.human_attribute_name(:data) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @syncs.each do |sync| %>
      <tr>
        <td><%= link_to sync.id, admin_sync_path(sync) %></td>
        <td><%= sync.header %></td>
        <td><%=l sync.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admin_sync_path(sync), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      admin_sync_path(sync),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class='pagination'>
  <%= paginate @syncs %>
</div>

app/views/admin/syncs/new.html.erb
<%- model_class = Sync -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/syncs/show.html.erb
<%- model_class = Sync -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:data) %>:</strong></dt>
  <dd><%= @sync.data %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              admin_syncs_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_admin_sync_path(@sync), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              admin_sync_path(@sync),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>