config/routes.rb
EmoneyServer::Application.routes.draw do
  namespace :api do
    namespace :v1 do
      devise_scope :user do
        post 'sessions' => 'sessions#create', :as => 'login'
        delete 'sessions' => 'sessions#destroy', :as => 'logout'
      end
    end
  end
  
  namespace :admin do
    resources :users do
      resources :accounts
    end
    resources :syncs
  end
  resources :presence_logs
  resources :park_logs
  resources :accounts do
    member do
      get :top_up
      post :process_top_up
    end
    resources :transaction_logs do
      get :cancel, on: :member
    end
    resources :presence_logs
    resources :park_logs
  end
  resources :payers, controller: "accounts" do
    resources :transaction_logs do
      get :cancel, on: :member
    end
  end
  resources :merchants, controller: "accounts" do
    resources :transaction_logs do
      get :cancel, on: :member
    end
  end
  
  resources :park_meters, controller: "accounts" do
    resources :park_logs
  end
  
  resources :attendance_machines, controller: "accounts" do
    resources :presence_logs do
      
    end
  end
  devise_for :users
  devise_scope :user do
    get '/logout' => "devise/sessions#destroy"
    get '/profile' => "devise/registrations#edit"
  end
  
  get '/update_key' => "home#update_key"
  get '/create_account/:account' => "accounts#create_account"
  post '/sync' => "transaction_logs#sync"
  post '/register' => "accounts#register"
  post '/presence' => "presence_logs#presence"
  post '/park' => "park_logs#park"
  post '/get_key' => "accounts#get_key"
  

  root 'home#index'
  get "/dashboard" => "home#index"

end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  field :locked_at,       :type => Time

  field :first_name
  field :last_name
  field :identity_number
  field :address
  field :phone
  #field :public_key
  field :is_admin, type: Boolean, default: false
  field :authentication_token
  has_many :accounts, dependent: :destroy
  has_many :payers, dependent: :destroy
  has_many :merchants, dependent: :destroy
  has_many :attendance_machines, dependent: :destroy
  has_many :park_meters, dependent: :destroy

  before_save :ensure_authentication_token
  after_create :create_payer_account, :create_merchant_account
  accepts_nested_attributes_for :accounts
  def self.columns
    self.fields.collect{|c| c[1]}
  end

  def create_payer_account(balance=0.0)
    payers.create(balance: balance, name: "Example Payer")
  end

  def create_merchant_account(balance=0.0)
    merchants.create(balance: balance, name: "Example Merchant")
  end
  
  def create_attendance_machine_account
    attendance_machines.create
  end
  
  def create_park_meter_account
    park_meters.create
  end

  def ensure_authentication_token
    if authentication_token.blank?
      self.authentication_token = generate_authentication_token
    end
  end

  private
  def generate_authentication_token
    loop do
      token = Devise.friendly_token
      break token unless User.where(authentication_token: token).first
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < InheritedResources::Base
  before_filter :authenticate_user!
  load_and_authorize_resource :user
  
  protected
  def permitted_params
    params.permit(user: [:email, :first_name, :last_name, :phone, :identity_number, :password, :password_confirmation])
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.erb
<%= simple_form_for [:admin, @user], :html => { :class => 'form-vertical' } do |f| %>
  <%= f.input :email %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :identity_number %>
  <%= f.input :address %>
  <%= f.input :phone %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                admin_users_path, :class => 'btn btn-default' %>
<% end %>

app/views/admin/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<div class="pull-right">
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_admin_user_path,
            :class => 'btn btn-primary' %>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:first_name) %></th>
      <th><%= model_class.human_attribute_name(:last_name) %></th>
      <th><%= model_class.human_attribute_name(:identity_number) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, admin_user_path(user) %></td>
        <td><%= user.email %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.identity_number %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admin_user_path(user), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      admin_user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:encrypted_password) %>:</strong></dt>
  <dd><%= @user.encrypted_password %></dd>
  <dt><strong><%= model_class.human_attribute_name(:reset_password_token) %>:</strong></dt>
  <dd><%= @user.reset_password_token %></dd>
  <dt><strong><%= model_class.human_attribute_name(:reset_password_sent_at) %>:</strong></dt>
  <dd><%= @user.reset_password_sent_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:remember_created_at) %>:</strong></dt>
  <dd><%= @user.remember_created_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:current_sign_in_at) %>:</strong></dt>
  <dd><%= @user.current_sign_in_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_sign_in_at) %>:</strong></dt>
  <dd><%= @user.last_sign_in_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:current_sign_in_ip) %>:</strong></dt>
  <dd><%= @user.current_sign_in_ip %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_sign_in_ip) %>:</strong></dt>
  <dd><%= @user.last_sign_in_ip %></dd>
  <dt><strong><%= model_class.human_attribute_name(:failed_attempts) %>:</strong></dt>
  <dd><%= @user.failed_attempts %></dd>
  <dt><strong><%= model_class.human_attribute_name(:unlock_token) %>:</strong></dt>
  <dd><%= @user.unlock_token %></dd>
  <dt><strong><%= model_class.human_attribute_name(:locked_at) %>:</strong></dt>
  <dd><%= @user.locked_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:first_name) %>:</strong></dt>
  <dd><%= @user.first_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_name) %>:</strong></dt>
  <dd><%= @user.last_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:identity_number) %>:</strong></dt>
  <dd><%= @user.identity_number %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @user.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd><%= @user.phone %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              admin_users_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_admin_user_path(@user), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              admin_user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>