config/routes.rb
EmoneyServer::Application.routes.draw do
  namespace :api do
    namespace :v1 do
      devise_scope :user do
        post 'sessions' => 'sessions#create', :as => 'login'
        delete 'sessions' => 'sessions#destroy', :as => 'logout'
      end
    end
  end
  
  namespace :admin do
    resources :users do
      resources :accounts
    end
    resources :syncs
  end
  resources :presence_logs
  resources :park_logs
  resources :accounts do
    member do
      get :top_up
      post :process_top_up
    end
    resources :transaction_logs do
      get :cancel, on: :member
    end
    resources :presence_logs
    resources :park_logs
  end
  resources :payers, controller: "accounts" do
    resources :transaction_logs do
      get :cancel, on: :member
    end
  end
  resources :merchants, controller: "accounts" do
    resources :transaction_logs do
      get :cancel, on: :member
    end
  end
  
  resources :park_meters, controller: "accounts" do
    resources :park_logs
  end
  
  resources :attendance_machines, controller: "accounts" do
    resources :presence_logs do
      
    end
  end
  devise_for :users
  devise_scope :user do
    get '/logout' => "devise/sessions#destroy"
    get '/profile' => "devise/registrations#edit"
  end
  
  get '/update_key' => "home#update_key"
  get '/create_account/:account' => "accounts#create_account"
  post '/sync' => "transaction_logs#sync"
  post '/register' => "accounts#register"
  post '/presence' => "presence_logs#presence"
  post '/park' => "park_logs#park"
  post '/get_key' => "accounts#get_key"
  

  root 'home#index'
  get "/dashboard" => "home#index"

end

app/models/account.rb
class Account
  include Mongoid::Document
  include Mongoid::Timestamps
  belongs_to :user
  embeds_many :transaction_logs, cascade_callbacks: true
  has_many :presence_logs
  has_many :park_logs

  field :balance, type: Float
  field :accn
  field :imei
  field :name
  validates :accn, presence: true, uniqueness: true
  before_validation :set_accn
  has_many :syncs
  def self.columns
    self.fields.collect{|c| c[1]}
  end
  
  def set_accn(force=false)
    begin
      if _type == "Merchant"
        number = "1"
      elsif _type == "Payer"
        number = "2"
      elsif _type == "AttendanceMachine"
        number = "3"
      else
        number = "4"
      end
      charset = %w{ 1 2 3 5 7 9}
      number = number + (0...13).map{ charset.to_a[rand(charset.size)] }.join  
    end while Account.where(:accn => number).exists?
    self.accn = number if self.new_record? || force
  end
  
  def is_merchant?
    _type == "Merchant"
  end
  
  def is_payer?
    _type == "Payer"
  end
  
  def is_presence?
    _type == "AttendanceMachine"
  end
  
  def is_park_meter?
    _type == "ParkMeter"
  end
end

app/controllers/accounts_controller.rb
class AccountsController < InheritedResources::Base
  before_filter :authenticate_user!, except: [:register, :get_key]
  skip_before_filter :verify_authenticity_token, only: :register, :if => Proc.new { |c| c.request.format == 'application/json' }

  def index
    @accounts = current_user.accounts.order_by("updated_at desc").page(params[:page]).per(10)
    #@accounts = Account.order_by("updated_at desc").page(params[:page]).per(10)
  end
  
  def top_up
    @account = Account.find params[:id]
    @transaction_log = @account.transaction_logs.build(log_type: "TopUp")
  end
  
  def create_account
    if params["account"] == "merchant"
      account = current_user.create_merchant_account
    elsif params["account"] == "payer"
      account = current_user.create_payer_account
    elsif params["account"] == "park_meter"
      account = current_user.create_park_meter_account
    else
      account = current_user.create_attendance_machine_account
    end
    redirect_to account
  end
  
  def get_key
    account = Account.where(accn: params["ACCN"].to_s).first
    @server = ServerSetting.first
    if account
      last_sync_at = params["last_sync_at"].to_i # to generate new key
      @renew_key = false
      if last_sync_at < @server.updated_at.to_i
        @renew_key = true
        @key = @server.key
      end
    else
      @error = "account not found"
    end
    respond_to do |format|
      format.json
      format.html
    end
  end
  
  def register
    data = JSON.parse params[:data].to_s
    @account = Account.where(accn: data["ACCN"].to_s).first
    @server = ServerSetting.first
    if @account
      if @account.imei.present?
        @error = "Already registered"
      else
        @account.update_attributes(imei: data["HWID"].to_s)
        @key = ServerSetting.first.key
      end
    else
      @error = "Account not found"
    end
    respond_to do |format|
      format.json
    end
  end
  
  def process_top_up
    @account = Account.find params[:id]
    @transaction_log = @account.transaction_logs.build(top_up_params)
    if @transaction_log.save
      redirect_to account_transaction_logs_path @account
    else
      render :top_up
    end
  end
  
  def top_up_params
    params.require(:transaction_log).permit([:amount, :log_type])
  end
  
  private

  def permitted_params
    params.permit(account: [:imei, :accn, :balance, :_type, :name])
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= simple_form_for @account, as: "account", :html => { :class => 'form-vertical' } do |f| %>
  <%= f.input :name %>
  <% if @account.is_merchant? %>
    <%= f.input :first_name, :required => true, :autofocus => true %>
    <%= f.input :last_name, :required => true %>
    <%= f.input :identity_number, :required => true %>
    <%= f.input :address, :required => true %>
    <%= f.input :phone, :required => true %>
    <%= f.input :email, :required => true %>
    <%= f.input :bank_account_number %>
  <% end %>
  
  <%= f.input :accn %>
  <%= f.input :imei %>
  <%= f.input :balance %>
  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                accounts_path, :class => 'btn btn-default' %>
<% end %>

app/views/accounts/edit.html.erb
<%- model_class = @account.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/accounts/index.html.erb
<%- model_class = Account -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<div class="pull-right">
<%= link_to raw("<i class='icon-plus'></i> Create Merchant"),
            "/create_account/merchant",
            :class => 'btn btn-success' %>
<%= link_to raw("<i class='icon-plus'></i> Create Payer"),
            "/create_account/payer",
            :class => 'btn btn-warning' %>
<%= link_to raw("<i class='icon-plus'></i> Create Attendance Machine"),
            "/create_account/attendance_machine",
            :class => 'btn btn-info' %>
<%= link_to raw("<i class='icon-plus'></i> Create Park Meter"),
            "/create_account/park_meter",
            :class => 'btn btn-warning' %>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:accn) %></th>
      <th><%= model_class.human_attribute_name(:imei) %></th>
      <th><%= model_class.human_attribute_name(:type) %></th>
      <th><%= model_class.human_attribute_name(:balance) %></th>
      <th><%= model_class.human_attribute_name(:last_update) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.name %></td>
        <td><%= link_to account.accn, account_path(account) %></td>
        <td><%= account.imei %></td>
        <td><%= account._type %></td>
        <td><%= number_to_currency account.balance, unit: "Rp " %></td>
        <td><%= account.updated_at.strftime("%Y-%m-%d %H:%M") %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_account_path(account), :class => 'btn btn-default btn-xs' %>
          <%= link_to "TopUp", top_up_account_path(account), class: "btn btn-xs btn-info" if account.is_payer? || account.is_merchant? %>
          <%= link_to "Park", account_park_logs_path(account), class: "btn btn-xs btn-warning" if account.is_park_meter? %>
          <%= link_to "Logs", account_transaction_logs_path(account), class: "btn btn-xs btn-success" if !account.is_presence? && !account.is_park_meter? %>
          <%= link_to "Presence", account_presence_logs_path(account), class: "btn btn-xs btn-warning" if account.is_presence? %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      account_path(account),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="pagination">
  <%= paginate @accounts %>
</div>

app/views/accounts/new.html.erb
<%- model_class = Account -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/accounts/show.html.erb
<%- model_class = Account -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @account.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:type) %>:</strong></dt>
  <dd><%= @account._type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:accn) %>:</strong></dt>
  <dd><%= @account.accn %></dd>
  <dt><strong><%= model_class.human_attribute_name(:imei) %>:</strong></dt>
  <dd><%= @account.imei %></dd>
  <dt><strong><%= model_class.human_attribute_name(:balance) %>:</strong></dt>
  <dd><%= @account.balance %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              accounts_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_account_path(@account), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              account_path(@account),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/accounts/top_up.html.erb
<h3>Top Up</h3>
<%= simple_form_for @transaction_log, url: process_top_up_account_url(@account, @transaction_log), :html => { :class => 'form-vertical' } do |f| %>
  <div class="form-inputs">
    <%= f.input :amount %>
    <%= f.input :log_type, as: :hidden %>
  </div>
  <br/>
  <div class="form-actions">
  <%= f.button :submit, "Top Up", :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                accounts_path, :class => 'btn btn-default' %>
  </div>
<% end %>